const mongoose=require('mongoose')
const schema=new mongoose.Schema(
    {
        flight_no:
        {
            type:String,
            required:true
        },
        flight_name:
        {
            type:String,
            required:true
        },
        start_location:
        {
            type:String,
            required:true
        },
        destination_location:
        {
            type:String,
            required:true
        },
        availableseats:
        {
            type:Number,
            default:60
        },
        date:
        {
            type:String,
            required:true
        },
        arrival_time:
        {
            type:String,
            required:true
        },
        departure_time:
        {
            type:String,
            required:true
        },
        passenger:
        {
            type:[]
        }
    }
)
const flightmodel=mongoose.model("Admin",schema);
module.exports=flightmodel;