const mongoose=require('mongoose')
const schema=new mongoose.Schema(
    {
        flight_no:
        {
            type:String,
            required:true
        },
        flight_name:
        {
            type:String,
            required:true
        },
        start_location:
        {
            type:String,
            required:true
        },
        destination_location:
        {
            type:String,
            required:true
        },
        availableseats:
        {
            type:Number,
            default:60
        },
        landing_date:
        {
            type:Date,
            required:true
        },
        landing_time:
        {
            type:Date,
            required:true
        },
        departure_date:
        {
            type:Date,
            required:true
        },
        departure_time:
        {
            type:Date,
            required:true
        },
        price:
        {
            type:Number,
            required:true

        }
    }
)
const flightmodel=mongoose.model("Admin",schema);
module.exports=flightmodel;